#! /usr/bin/env zsh

alias l='ls'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ls -Alh'
alias sl='ls'
alias lsdir='ls -d */'
alias duc='du -chs'
alias sizeof='duc'
alias df='df -h'
alias free='free -m'
alias ttop='top -ocpu -R -F -s 2 -n30'

alias gcc_macros='gcc -E -dM - </dev/null | sort'

#when previous command fails, run fu to rerun command as sudo
alias fu='sudo $(fc -ln -1)'


alias VBoxManage='VBoxManage -q'
alias vb='VBoxManage -q'
alias vbh='VBoxHeadless'
alias vbhs='VBoxHeadless -startvm'


alias matlab='matlab -nodesktop -nodisplay -nosplash'

alias configure-local='./configure --prefix=$HOME/.local'
