#! /usr/bin/env zsh

function title() {
	# escape '%' chars in $1, make nonprintables visible
	  a=${(V)1//\%/\%\%}

	# Truncate command, and join lines.
	  a=$(print -Pn "%40>...>$a" | tr -d "\n")

	  case $TERM in
	      screen*)
            #print -Pn "\e]2;$a @ $2\a" # plain xterm title
            #print -Pn "\ek$a\e\\"      # screen title (in ^A")
            #print -Pn "\e_$2   \e\\"   # screen location
            ;;
        xterm*|rxvt)
            print -Pn "\e]2;$a @ $2\a" # plain xterm title
            ;;
    esac
}

#precmd is called just before the prompt is printed
function precmd() {
	  title "zsh" "%m(%55<...<%~)"
}

# preexec is called just before any command line is executed
function preexec() {
	  title "$1" "%m(%35<...<%~)"
}

#### PROMPT ####
autoload colors zsh/terminfo
if [[ "$terminfo[colors]" -ge 8 ]]; then
	colors
fi

for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
	eval PR_${color}='%{$terminfo[bold]$fg[${(L)color}]%}'
	eval PR_LIGHT_${color}='%{$fg[${(L)color}]%}'
done
PR_NO_COLOR="%{$terminfo[sgr0]%}"
PROMPT="$PR_BLUE%n$PR_WHITE$@$PR_LIGHT_BLUE$%m$PR_WHITE:$PR_GREEN$%c [%h | %L | %?]%# $PR_NO_COLOR"

# case $TERM in
# 	  screen*|xterm*|rxvt|linux|eterm-color)
# 		    PROMPT="$PR_BLUE%n$PR_WHITE$@$PR_LIGHT_BLUE$%m$PR_WHITE:$PR_GREEN$%c [%h | %?]%# $PR_NO_COLOR"
# 		    ;;
# 	  *)
# 		    PROMPT="$PR_BLUE%n$PR_WHITE$@$PR_LIGHT_BLUE$%m$PR_WHITE:$PR_GREEN$%c [%h | %j]%~ $PR_NO_COLOR"
# esac
