#! /usr/bin/env zsh

#export RSENSE_HOME=${HOME}/local/rsense

typeset -xUT GEM_HOME gem_home
gem_home=(${HOME}/.gem/ruby/1.8(N))

typeset -xUT GEM_PATH gem_path
gem_path=($gem_home /usr/lib/ruby/gems/1.8(N))

typeset -xUT RUBYLIB rubylib
rubylib=(${HOME}/local/lib(N) $rubylib)

path=($gem_home/bin(N) $path)
